version: '3.4'

services:
  devtoolcompany:
    image: parkjugod.asuscomm.com:5000/devtoolcompany:0.1
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 8080:80
    expose:
      - 8080 
